// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.github.jrbase.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Request_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Request_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListStr_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListStr_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\"r\n\007Request\022\013\n\003cmd\030\001 \001(\005\022" +
      "\013\n\003key\030\002 \001(\t\022\022\n\010valueStr\030\003 \001(\tH\000\022\022\n\010valu" +
      "eInt\030\004 \001(\005H\000\022\033\n\007listStr\030\005 \001(\0132\010.ListStrH" +
      "\000B\010\n\006values\"\031\n\007ListStr\022\016\n\006values\030\001 \003(\t\"\031" +
      "\n\010Response\022\r\n\005value\030\001 \001(\t21\n\nCmdService\022" +
      "#\n\nrequestCmd\022\010.Request\032\t.Response\"\000B$\n\027" +
      "org.github.jrbase.protoB\007MessageP\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Request_descriptor,
        new java.lang.String[] { "Cmd", "Key", "ValueStr", "ValueInt", "ListStr", "Values", });
    internal_static_ListStr_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ListStr_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListStr_descriptor,
        new java.lang.String[] { "Values", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
