// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package org.github.jrbase.proto;

/**
 * Protobuf type {@code Request}
 */
public  final class Request extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Request)
    RequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Request.newBuilder() to construct.
  private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Request() {
    key_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Request();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Request(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            cmd_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            key_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            valuesCase_ = 3;
            values_ = s;
            break;
          }
          case 32: {
            valuesCase_ = 4;
            values_ = input.readInt32();
            break;
          }
          case 42: {
            org.github.jrbase.proto.ListStr.Builder subBuilder = null;
            if (valuesCase_ == 5) {
              subBuilder = ((org.github.jrbase.proto.ListStr) values_).toBuilder();
            }
            values_ =
                input.readMessage(org.github.jrbase.proto.ListStr.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((org.github.jrbase.proto.ListStr) values_);
              values_ = subBuilder.buildPartial();
            }
            valuesCase_ = 5;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.github.jrbase.proto.Message.internal_static_Request_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.github.jrbase.proto.Message.internal_static_Request_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.github.jrbase.proto.Request.class, org.github.jrbase.proto.Request.Builder.class);
  }

  private int valuesCase_ = 0;
  private java.lang.Object values_;
  public enum ValuesCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    VALUESTR(3),
    VALUEINT(4),
    LISTSTR(5),
    VALUES_NOT_SET(0);
    private final int value;
    private ValuesCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValuesCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValuesCase forNumber(int value) {
      switch (value) {
        case 3: return VALUESTR;
        case 4: return VALUEINT;
        case 5: return LISTSTR;
        case 0: return VALUES_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValuesCase
  getValuesCase() {
    return ValuesCase.forNumber(
        valuesCase_);
  }

  public static final int CMD_FIELD_NUMBER = 1;
  private int cmd_;
  /**
   * <code>int32 cmd = 1;</code>
   * @return The cmd.
   */
  public int getCmd() {
    return cmd_;
  }

  public static final int KEY_FIELD_NUMBER = 2;
  private volatile java.lang.Object key_;
  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUESTR_FIELD_NUMBER = 3;
  /**
   * <code>string valueStr = 3;</code>
   * @return The valueStr.
   */
  public java.lang.String getValueStr() {
    java.lang.Object ref = "";
    if (valuesCase_ == 3) {
      ref = values_;
    }
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (valuesCase_ == 3) {
        values_ = s;
      }
      return s;
    }
  }
  /**
   * <code>string valueStr = 3;</code>
   * @return The bytes for valueStr.
   */
  public com.google.protobuf.ByteString
      getValueStrBytes() {
    java.lang.Object ref = "";
    if (valuesCase_ == 3) {
      ref = values_;
    }
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      if (valuesCase_ == 3) {
        values_ = b;
      }
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VALUEINT_FIELD_NUMBER = 4;
  /**
   * <code>int32 valueInt = 4;</code>
   * @return The valueInt.
   */
  public int getValueInt() {
    if (valuesCase_ == 4) {
      return (java.lang.Integer) values_;
    }
    return 0;
  }

  public static final int LISTSTR_FIELD_NUMBER = 5;
  /**
   * <code>.ListStr listStr = 5;</code>
   * @return Whether the listStr field is set.
   */
  public boolean hasListStr() {
    return valuesCase_ == 5;
  }
  /**
   * <code>.ListStr listStr = 5;</code>
   * @return The listStr.
   */
  public org.github.jrbase.proto.ListStr getListStr() {
    if (valuesCase_ == 5) {
       return (org.github.jrbase.proto.ListStr) values_;
    }
    return org.github.jrbase.proto.ListStr.getDefaultInstance();
  }
  /**
   * <code>.ListStr listStr = 5;</code>
   */
  public org.github.jrbase.proto.ListStrOrBuilder getListStrOrBuilder() {
    if (valuesCase_ == 5) {
       return (org.github.jrbase.proto.ListStr) values_;
    }
    return org.github.jrbase.proto.ListStr.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cmd_ != 0) {
      output.writeInt32(1, cmd_);
    }
    if (!getKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, key_);
    }
    if (valuesCase_ == 3) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, values_);
    }
    if (valuesCase_ == 4) {
      output.writeInt32(
          4, (int)((java.lang.Integer) values_));
    }
    if (valuesCase_ == 5) {
      output.writeMessage(5, (org.github.jrbase.proto.ListStr) values_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (cmd_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, cmd_);
    }
    if (!getKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, key_);
    }
    if (valuesCase_ == 3) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, values_);
    }
    if (valuesCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(
            4, (int)((java.lang.Integer) values_));
    }
    if (valuesCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (org.github.jrbase.proto.ListStr) values_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.github.jrbase.proto.Request)) {
      return super.equals(obj);
    }
    org.github.jrbase.proto.Request other = (org.github.jrbase.proto.Request) obj;

    if (getCmd()
        != other.getCmd()) return false;
    if (!getKey()
        .equals(other.getKey())) return false;
    if (!getValuesCase().equals(other.getValuesCase())) return false;
    switch (valuesCase_) {
      case 3:
        if (!getValueStr()
            .equals(other.getValueStr())) return false;
        break;
      case 4:
        if (getValueInt()
            != other.getValueInt()) return false;
        break;
      case 5:
        if (!getListStr()
            .equals(other.getListStr())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CMD_FIELD_NUMBER;
    hash = (53 * hash) + getCmd();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    switch (valuesCase_) {
      case 3:
        hash = (37 * hash) + VALUESTR_FIELD_NUMBER;
        hash = (53 * hash) + getValueStr().hashCode();
        break;
      case 4:
        hash = (37 * hash) + VALUEINT_FIELD_NUMBER;
        hash = (53 * hash) + getValueInt();
        break;
      case 5:
        hash = (37 * hash) + LISTSTR_FIELD_NUMBER;
        hash = (53 * hash) + getListStr().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.github.jrbase.proto.Request parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.jrbase.proto.Request parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.jrbase.proto.Request parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.jrbase.proto.Request parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.jrbase.proto.Request parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.github.jrbase.proto.Request parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.github.jrbase.proto.Request parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.github.jrbase.proto.Request parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.github.jrbase.proto.Request parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.github.jrbase.proto.Request parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.github.jrbase.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.github.jrbase.proto.Request parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.github.jrbase.proto.Request prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Request}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Request)
      org.github.jrbase.proto.RequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.github.jrbase.proto.Message.internal_static_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.github.jrbase.proto.Message.internal_static_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.github.jrbase.proto.Request.class, org.github.jrbase.proto.Request.Builder.class);
    }

    // Construct using org.github.jrbase.proto.Request.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      cmd_ = 0;

      key_ = "";

      valuesCase_ = 0;
      values_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.github.jrbase.proto.Message.internal_static_Request_descriptor;
    }

    @java.lang.Override
    public org.github.jrbase.proto.Request getDefaultInstanceForType() {
      return org.github.jrbase.proto.Request.getDefaultInstance();
    }

    @java.lang.Override
    public org.github.jrbase.proto.Request build() {
      org.github.jrbase.proto.Request result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.github.jrbase.proto.Request buildPartial() {
      org.github.jrbase.proto.Request result = new org.github.jrbase.proto.Request(this);
      result.cmd_ = cmd_;
      result.key_ = key_;
      if (valuesCase_ == 3) {
        result.values_ = values_;
      }
      if (valuesCase_ == 4) {
        result.values_ = values_;
      }
      if (valuesCase_ == 5) {
        if (listStrBuilder_ == null) {
          result.values_ = values_;
        } else {
          result.values_ = listStrBuilder_.build();
        }
      }
      result.valuesCase_ = valuesCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.github.jrbase.proto.Request) {
        return mergeFrom((org.github.jrbase.proto.Request)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.github.jrbase.proto.Request other) {
      if (other == org.github.jrbase.proto.Request.getDefaultInstance()) return this;
      if (other.getCmd() != 0) {
        setCmd(other.getCmd());
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        onChanged();
      }
      switch (other.getValuesCase()) {
        case VALUESTR: {
          valuesCase_ = 3;
          values_ = other.values_;
          onChanged();
          break;
        }
        case VALUEINT: {
          setValueInt(other.getValueInt());
          break;
        }
        case LISTSTR: {
          mergeListStr(other.getListStr());
          break;
        }
        case VALUES_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.github.jrbase.proto.Request parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.github.jrbase.proto.Request) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int valuesCase_ = 0;
    private java.lang.Object values_;
    public ValuesCase
        getValuesCase() {
      return ValuesCase.forNumber(
          valuesCase_);
    }

    public Builder clearValues() {
      valuesCase_ = 0;
      values_ = null;
      onChanged();
      return this;
    }


    private int cmd_ ;
    /**
     * <code>int32 cmd = 1;</code>
     * @return The cmd.
     */
    public int getCmd() {
      return cmd_;
    }
    /**
     * <code>int32 cmd = 1;</code>
     * @param value The cmd to set.
     * @return This builder for chaining.
     */
    public Builder setCmd(int value) {
      
      cmd_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 cmd = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCmd() {
      
      cmd_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 2;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 2;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 2;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <code>string key = 2;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      key_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>string valueStr = 3;</code>
     * @return The valueStr.
     */
    public java.lang.String getValueStr() {
      java.lang.Object ref = "";
      if (valuesCase_ == 3) {
        ref = values_;
      }
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (valuesCase_ == 3) {
          values_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string valueStr = 3;</code>
     * @return The bytes for valueStr.
     */
    public com.google.protobuf.ByteString
        getValueStrBytes() {
      java.lang.Object ref = "";
      if (valuesCase_ == 3) {
        ref = values_;
      }
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (valuesCase_ == 3) {
          values_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string valueStr = 3;</code>
     * @param value The valueStr to set.
     * @return This builder for chaining.
     */
    public Builder setValueStr(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  valuesCase_ = 3;
      values_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string valueStr = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearValueStr() {
      if (valuesCase_ == 3) {
        valuesCase_ = 0;
        values_ = null;
        onChanged();
      }
      return this;
    }
    /**
     * <code>string valueStr = 3;</code>
     * @param value The bytes for valueStr to set.
     * @return This builder for chaining.
     */
    public Builder setValueStrBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      valuesCase_ = 3;
      values_ = value;
      onChanged();
      return this;
    }

    /**
     * <code>int32 valueInt = 4;</code>
     * @return The valueInt.
     */
    public int getValueInt() {
      if (valuesCase_ == 4) {
        return (java.lang.Integer) values_;
      }
      return 0;
    }
    /**
     * <code>int32 valueInt = 4;</code>
     * @param value The valueInt to set.
     * @return This builder for chaining.
     */
    public Builder setValueInt(int value) {
      valuesCase_ = 4;
      values_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 valueInt = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearValueInt() {
      if (valuesCase_ == 4) {
        valuesCase_ = 0;
        values_ = null;
        onChanged();
      }
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        org.github.jrbase.proto.ListStr, org.github.jrbase.proto.ListStr.Builder, org.github.jrbase.proto.ListStrOrBuilder> listStrBuilder_;
    /**
     * <code>.ListStr listStr = 5;</code>
     * @return Whether the listStr field is set.
     */
    public boolean hasListStr() {
      return valuesCase_ == 5;
    }
    /**
     * <code>.ListStr listStr = 5;</code>
     * @return The listStr.
     */
    public org.github.jrbase.proto.ListStr getListStr() {
      if (listStrBuilder_ == null) {
        if (valuesCase_ == 5) {
          return (org.github.jrbase.proto.ListStr) values_;
        }
        return org.github.jrbase.proto.ListStr.getDefaultInstance();
      } else {
        if (valuesCase_ == 5) {
          return listStrBuilder_.getMessage();
        }
        return org.github.jrbase.proto.ListStr.getDefaultInstance();
      }
    }
    /**
     * <code>.ListStr listStr = 5;</code>
     */
    public Builder setListStr(org.github.jrbase.proto.ListStr value) {
      if (listStrBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        values_ = value;
        onChanged();
      } else {
        listStrBuilder_.setMessage(value);
      }
      valuesCase_ = 5;
      return this;
    }
    /**
     * <code>.ListStr listStr = 5;</code>
     */
    public Builder setListStr(
        org.github.jrbase.proto.ListStr.Builder builderForValue) {
      if (listStrBuilder_ == null) {
        values_ = builderForValue.build();
        onChanged();
      } else {
        listStrBuilder_.setMessage(builderForValue.build());
      }
      valuesCase_ = 5;
      return this;
    }
    /**
     * <code>.ListStr listStr = 5;</code>
     */
    public Builder mergeListStr(org.github.jrbase.proto.ListStr value) {
      if (listStrBuilder_ == null) {
        if (valuesCase_ == 5 &&
            values_ != org.github.jrbase.proto.ListStr.getDefaultInstance()) {
          values_ = org.github.jrbase.proto.ListStr.newBuilder((org.github.jrbase.proto.ListStr) values_)
              .mergeFrom(value).buildPartial();
        } else {
          values_ = value;
        }
        onChanged();
      } else {
        if (valuesCase_ == 5) {
          listStrBuilder_.mergeFrom(value);
        }
        listStrBuilder_.setMessage(value);
      }
      valuesCase_ = 5;
      return this;
    }
    /**
     * <code>.ListStr listStr = 5;</code>
     */
    public Builder clearListStr() {
      if (listStrBuilder_ == null) {
        if (valuesCase_ == 5) {
          valuesCase_ = 0;
          values_ = null;
          onChanged();
        }
      } else {
        if (valuesCase_ == 5) {
          valuesCase_ = 0;
          values_ = null;
        }
        listStrBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.ListStr listStr = 5;</code>
     */
    public org.github.jrbase.proto.ListStr.Builder getListStrBuilder() {
      return getListStrFieldBuilder().getBuilder();
    }
    /**
     * <code>.ListStr listStr = 5;</code>
     */
    public org.github.jrbase.proto.ListStrOrBuilder getListStrOrBuilder() {
      if ((valuesCase_ == 5) && (listStrBuilder_ != null)) {
        return listStrBuilder_.getMessageOrBuilder();
      } else {
        if (valuesCase_ == 5) {
          return (org.github.jrbase.proto.ListStr) values_;
        }
        return org.github.jrbase.proto.ListStr.getDefaultInstance();
      }
    }
    /**
     * <code>.ListStr listStr = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.github.jrbase.proto.ListStr, org.github.jrbase.proto.ListStr.Builder, org.github.jrbase.proto.ListStrOrBuilder> 
        getListStrFieldBuilder() {
      if (listStrBuilder_ == null) {
        if (!(valuesCase_ == 5)) {
          values_ = org.github.jrbase.proto.ListStr.getDefaultInstance();
        }
        listStrBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.github.jrbase.proto.ListStr, org.github.jrbase.proto.ListStr.Builder, org.github.jrbase.proto.ListStrOrBuilder>(
                (org.github.jrbase.proto.ListStr) values_,
                getParentForChildren(),
                isClean());
        values_ = null;
      }
      valuesCase_ = 5;
      onChanged();;
      return listStrBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Request)
  }

  // @@protoc_insertion_point(class_scope:Request)
  private static final org.github.jrbase.proto.Request DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.github.jrbase.proto.Request();
  }

  public static org.github.jrbase.proto.Request getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Request>
      PARSER = new com.google.protobuf.AbstractParser<Request>() {
    @java.lang.Override
    public Request parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Request(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Request> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Request> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.github.jrbase.proto.Request getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

